### ISSUE TITLE
vendor/bin/skeleton ironically ignores .gitignore

### ISSUE THREAD

**Issue by jestho** [alkemann/h2l#23]
Makes the initial commit pretty nasty.

**Comment by alkemann** [comment]
You mean it adds vendor and node_modules? I tested pretty extensively that it doesnt. But maybe I also have that in my global .gitignore.  So it doesnt copy the .gitignore in the skeleton. Ok I think the correct change here is a -T option on cp. Will add asap

**Comment by alkemann** [comment]
-T didn't fix it.

**Comment by alkemann** [comment]
Fixed by https://github.com/alkemann/h2l/commit/93e07e29c9a3699edc3b2c9f3174a7228c829a1f
